src/Microsoft.VisualStudio.SlowCheetah.VS/NugetHandler/SlowCheetahNuGetManager.cs
Fixing check for new SlowCheetah package name
=> Fixing new package name

src/Microsoft.VisualStudio.SlowCheetah/Microsoft.VisualStudio.SlowCheetah.csproj
Adding assemblies to NuGet package
=> Adding assemblies to NuGet package

src/Microsoft.VisualStudio.SlowCheetah/Microsoft.VisualStudio.SlowCheetah.csproj
Make JDT package private asset
=> Making JDT private asset

README.md
Updating NuGet badge with correct link
=> Fixing NuGet badge

Restore.cmd
Adding more detailed message on restore script
Turning off echo
=> Fixing Restore script

version.json, vs/Microsoft.VisualStudio.SlowCheetah.Full.swixproj, vs/Microsoft.VisualStudio.SlowCheetah.vsmanproj
Bumping up version to reset git height
Adding MicroBuild.VisualStudio to the insertions projects
Getting it working with microbuild signing
=> Fixing insertion projects

src/Microsoft.VisualStudio.SlowCheetah.VS/NugetHandler/PackageHandlers/BackgroundInstallationHandler.cs, src/Microsoft.VisualStudio.SlowCheetah.VS/Package/AddTransformCommand.cs, src/Microsoft.VisualStudio.SlowCheetah.VS/Package/PreviewTransformCommand.cs, src/Microsoft.VisualStudio.SlowCheetah.VS/Package/SlowCheetahPackageLogger.cs, src/Microsoft.VisualStudio.SlowCheetah.VS/SlowCheetahPackage.cs, src/Microsoft.VisualStudio.SlowCheetah.VS/TransformationPreviewLogger.cs, src/Microsoft.VisualStudio.SlowCheetah.VS/Utilities/PackageUtilities.cs, src/Microsoft.VisualStudio.SlowCheetah/Transformer/TransformerFactory.cs, src/Microsoft.VisualStudio.SlowCheetah/Transformer/XmlTransformer.cs
Making changes for better security.
- string.Format
- StringComparison
- XmlDocument.Load
=> Security changes

doc/transforming_files.md
=> Fixing Nuget and extension links

.vsts-ci.yml
Changing output folder for CI build
=> Fix CI Build

src/Microsoft.VisualStudio.SlowCheetah/Transformer/XmlTransformer.cs
Some comparisons that would never hit.
=> fixes incorrect variable reference in XmlTransformer.cs

src/Microsoft.VisualStudio.SlowCheetah.Tests/BuildTests/TestProjects/ConsoleApp/ConsoleApp.csproj, src/Microsoft.VisualStudio.SlowCheetah.Tests/BuildTests/TestProjects/WebApplication/WebApplication.csproj, src/Microsoft.VisualStudio.SlowCheetah/Build/Microsoft.VisualStudio.SlowCheetah.targets
Despite the changes being justified, this is a breaking change. We can consider taking it in the future if necessary.
Reverts #169
=> Revert the changes to preserve copy to output

src/Microsoft.VisualStudio.SlowCheetah.Tests/Microsoft.VisualStudio.SlowCheetah.Tests.csproj
Fixing an accidental change in the previous PR - was using the wrong nuget package
=> Switching to the right NonShipping package

src/Microsoft.VisualStudio.SlowCheetah.VS.Tests/Microsoft.VisualStudio.SlowCheetah.VS.Tests.csproj
FIxing another nuget dependency that was missed in the previous PRs
=> Fixing another nuget dependency

README.md
for the different versions of Visual Studio
=> Updating readme to link the 2 versions of the extension

src/Microsoft.VisualStudio.SlowCheetah/Build/Microsoft.VisualStudio.SlowCheetah.targets
=> Remove needless backslash from task path

.vsts-ci.yml
Adding binskim scanning to the build pipeline.
=> Update pipeline to use bimskim

.vsts-ci.yml, azure-pipelines/TSAOptions.json, nuget.config
added automated runs for api scan and TSA onboarding..
=> Add api scan to pipeline

.vsts-ci.yml
Updated our pipeline to use updated apiscan authorization
=> changed apiscan task to use shared microbuild client id

src/Microsoft.VisualStudio.SlowCheetah.Vsix/Microsoft.VisualStudio.SlowCheetah.Vsix.csproj
The NOTICE is included already in nuget packages. However, that does not handle the produced vsix.
=> Include NOTICE in the vsix package

azure-pipelines/release.yml
Updating the service connnection for github releases.
=> udpate service connection for release
